name: Build on Tag (multi-OS + Arch)

on:
  push:
    tags:
      - 'v*'

jobs:
  # Build job
  build:
    continue-on-error: true
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:

          - runner: macos-latest
            arch: x64
          - runner: macos-latest
            arch: arm64

          - runner: ubuntu-latest
            arch: x64
          - runner: ubuntu-latest
            arch: arm64

          #- runner: debian-latest
          #  arch: x64

          - runner: windows-latest
            arch: x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Display runner info
        run: |
          echo "Running on ${{ matrix.runner }} - Arch: ${{ matrix.arch }}"
          uname -a || systeminfo


      - name: Run make
        shell: bash
        run: |
          echo "Build with make on ${{ matrix.runner }} (${{ matrix.arch }})"
          make


      - name: Archive binary
        run: |
          mkdir -p dist
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cp valkac.exe dist/valka-${{ matrix.runner }}-${{ matrix.arch }}.exe
          else
            cp valkac dist/valka-${{ matrix.runner }}-${{ matrix.arch }}
          fi
        shell: bash


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: valka-compiler-${{ matrix.runner }}-${{ matrix.arch }}
          path: dist/*


  # Release job
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
