name: Build on Tag (multi-OS + Arch)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:

          - runner: macos-latest
            arch: x64
          - runner: macos-latest
            arch: arm64


          - runner: ubuntu-latest
            arch: x64
          - runner: ubuntu-latest
            arch: arm64


          - runner: debian-latest
            arch: x64


          - runner: windows-latest
            arch: x64


          - runner: self-hosted
            arch: x64
            os: archlinux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display runner info
        run: |
            echo "Running on ${{ matrix.runner }} - Arch: ${{ matrix.arch }}"
            uname -a || systeminfo

      - name: Run make
        shell: bash
        run: |
            echo "Build with make on ${{ matrix.runner }} (${{ matrix.arch }})"
            make

